Fix: Environment mapsize limit reached
Error: Database error
        caused by: Error in LMDB: MDB_MAP_FULL: Environment mapsize limit reached
        caused by: MDB_MAP_FULL: Environment mapsize limit reached